---
- hosts: all
  become: true
  tasks:
  - name: install docker
    apt:
      pkg: docker.io
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
      enabled: true
  - name: Stop existing container
    command: docker stop bootcamp
  - name: Remove existing container
    command: docker rm bootcamp
  - name: run docker image
    command: docker run -it --name bootcamp -d -p 8888:8888 prashpb/bootcamp:1
  handlers:
  - name: run update
    apt:
      update_cache: yes